export const CARD_TAGS = [
  'Array',
  'Hash Table',
  'Monotonic Stack',
  'Binary Search',
  'String',
  'DP',
  'Greedy',
  'Math',
  'Two Pointers',
  'Intervals',
  'Backtracking',
  'Sorting',
  'Voting Algorithm',
  'Matrix',
  'Stack',
  'Heap',
  'Linked List',
  'Prefix Sum',
  'Bit Manipulation',
  'Graph',
  'BFS',
  'DFS',
  'Union Find',
  'Divide and Conquer',
  'Dynamic Programming',
  'Deque',
];
export const CARD_COURSES = ['KTLT', 'DSA'];
export const CARD_DIFFICULTIES = ['Easy', 'Medium', 'Hard'];
